### ISSUE TITLE
Discord 12.4.1 API upgrade issues

### ISSUE THREAD

**Issue by ct-bess** [ct-bess/Bean-Stalk#2]
1. `message.content.messages.last()` is apparently not a function anymore

2. sending `message.author` no longer *@'s* a user

   Have to do `<@!${message.author.id}>` now

3. `channels` isn't a collection anymore, so don't `forEach` it, you have to do `channels.cache` or somethin

**Comment by JOBBIN9422** [comment]
this is so sad :'(

**Comment by ct-bess** [comment]
:(((((((((((((((99((
Can WE hit 56000000 LIKES??///////////?????

**Comment by JOBBIN9422** [comment]
ok this is epic
