### ISSUE TITLE
Channel List command

### ISSUE THREAD

**Issue by MichaelHHall** [ct-bess/Bean-Stalk#5]
Currently we have the phenomenal `-yeet` command. But with no way to see the available channels, we lack a good way to reliably send messages to other servers which we may not be members of. the current workaround of a `$echo -yeet` loop is unreliable and a nuisance to the channels it lands in. I propose that we include a command to list all of the channels of which bean stalk is a member, including the name and ID of each channel (and possibly the server name if you can work out the formatting)

## Context

Most programs allow for a programmatic way of viewing all of the various options they can use in their commands. In many, that simply involves a list of args and their possible values being produced by the `--help` arg, but in some, there is an entirely separate command that lists out a database or other data to be used in a different command. Either of these approaches could be effective here.

## Possible Fix

The bot should have an attribute showing all of the guilds it is a member of. For example, the discord.py bot has a `bot.guilds` attribute that is a list of guilds. Ideally each guild object will have an attribute for all text channels (in discord.py it is `text_channels`). From here it would be simple to iterate over each guild and each text channel in turn and print output based on that.

**Comment by ct-bess** [comment]
ok expect a `-bean channels` soon :tm:
